### ISSUE TITLE
Timeline view error when adding a metric after deleting all metrics

### ISSUE THREAD

**Issue by wpj0110** [scarletstudio/transithealth#147] opened 2021-07-31 14:46 UTC
## Description
Error when adding a metric after deleting all metrics.
There are no errors for Weekly Rideshare pickups and Weekly COVID cases if you add one of them after deleting all the metrics. 
![temp3](https://user-images.githubusercontent.com/84047863/127743474-73c4aaad-b027-47fc-afa8-34b117841745.PNG)
After adding the Weekly Rideshare pickups metric,
![temp4](https://user-images.githubusercontent.com/84047863/127743550-3a4a863b-71a1-4061-b94e-3429813a96b8.PNG)
However, for all the rest, there is an error.

## To Reproduce

1. Delete all metrics in the timeline view
2. Add a metric (Note: If you add Weekly Rideshare pickups or Weekly COVID cases, there will be no error)
![temp5](https://user-images.githubusercontent.com/84047863/127743576-d8967b71-c754-410e-ac64-7c2d7b5a60ae.PNG)
3. Should be the error
![temp6](https://user-images.githubusercontent.com/84047863/127743592-b32e0751-c51d-4083-a6f8-27b042012595.PNG)
## Expected Behavior
Adding a metric after deleting all metrics should simply show a new timeline view of that newly added metric.

**Comment by vingkan** [comment] 2021-07-31 15:03
Duplicate of #127 but your documentation is much better so I will close that one and we will keep this one!

**Closed** 2021-08-02 04:09 UTC
Labels: app, bug
